### ISSUE TITLE
How to use binding {{}} instead of ng-bind?

### ISSUE THREAD

**Issue by Ewelina555** [angular-data-grid/angular-data-grid.github.io#15] opened 2016-09-13 16:12 UTC
I want to add a link with the binding in a grid-item like this:
`<a ng-href="book/{{item.id}}"/>` 
but the binding doesn't work. How can I do this? I get empty value. This works well:
`<span ng-bind="item.id">`
But I want an 'a' not  a span. How can I achieve this?

**Comment by AlexanderZhukCoherent** [comment] 2017-03-10 11:02
Cannot reproduce  - seems like fixed in the scope of recent refactoring.
@Ewelina555 - please try the latest version and let us know.

**Closed as completed by AlexanderZhukCoherent** 2017-03-10 11:02 UTC
Labels: cannot reproduce
