### ISSUE TITLE
sortCache does not work

### ISSUE THREAD

**Issue by saulsluz** [angular-data-grid/angular-data-grid.github.io#50] opened 2017-06-27 21:55 UTC
I tested in my application and in live demo. The bug is alive!

The steps:
1 . Perform any "filter"
2 . Perform any "sort"
3 . Remove the "filter"

The result is that you dont get all results again.
The feature "sortCache" inside applyFilters function not work properly.

A workaround is simple: just comment it.
```javascript
                //if ($scope.sortOptions.predicate && $scope.sortCache && $scope.sortCache.predicate === $scope.sortOptions.predicate
                //    && $scope.sortCache.direction === $scope.sortOptions.direction) {
                //    $scope.filtered = $scope.sortCache.data.slice();
                //    sorted = true;
                //} else {
                    $scope.filtered = $scope._gridOptions.data.slice();
                //}
```

**Comment by AndreyChayko** [comment] 2017-09-27 11:14
Issue closed as duplicate of [#57](https://github.com/angular-data-grid/angular-data-grid.github.io/issues/57)

**Closed as completed by AndreyChayko** 2017-09-27 11:14 UTC
